### ISSUE TITLE
Consumption not tracking properly

### ISSUE THREAD

**Issue by SolarPhoenix** [melroy999/RareTrackerMaw#2]
Consumption Rare has 3 ID for each of its stages,
179769 -> normal - doesnt drop the loot - tracked by addon
179755 -> rare - drops loot - not tracked 
179768 -> rare elite - same loot as rare - not tracked 
 
Not sure how to fix this you would need to track both ID's but only show one
If thats not possable, just track the rare

**Comment by melroy999** [comment]
Interesting... I am not entirely certain on the best approach to take here, since it is indeed not possible in the current implementation to merge multiple entities. However, given that this is an addon made primarily for tracking rares, it is probably best to change the ID to that of the rare/rare elite for now, with the appropriate tags in the name. I will take a look at this later today.

**Comment by melroy999** [comment]
I have uploaded a new version that has all three versions of consumption in the tracking list. Please let me know if the problem persists.
