### ISSUE TITLE
Observer Yorik not marked as killed

### ISSUE THREAD

**Issue by SolarPhoenix** [melroy999/RareTrackerMaw#5]
Not sure what is causing this. Might be the fact that Yorik remains rare even after killed.

**Comment by melroy999** [comment]
This is caused by missing data in the entries, since I didn't have access to the exact quest/kill tracking ID at the time. I will check whether there is an updated list of IDs yet.

**Comment by SolarPhoenix** [comment]
tech support speedrun

**Comment by melroy999** [comment]
Got to do something productive while waiting for rares to appear ^^.

**Comment by SolarPhoenix** [comment]
can i add you on bnet to ask you some questions

**Comment by melroy999** [comment]
I am sorry but, due to personal reasons, I am not really comfortable with adding more bnet friends... I will be more than happy to answer any questions you have here, though!

**Comment by SolarPhoenix** [comment]
kk, just wana say I love your mod. its a shame so little people use it. Anyway, just wondering how you find out all these event ids? Is it all from players looking at game logs?

**Comment by SolarPhoenix** [comment]
also why havent you done tracking for other zones, is it just not worth the time investment?

**Comment by melroy999** [comment]
Thank you! Aye, the addon does see little use, unfortunately so… but I think that is also because only a few people have real use of it. The addon is primarily made for those that actively and repeatedly farm rares for mounts or toys, which is only a small part of the playerbase.

Finding the daily kill mark quest IDs requires players to compare their list of completed quests before and after a rare kill. Fortunately, these IDs can be found on Wowpedia too at times, or alternatively, I can cross reference my own data with that of addons like Handynotes. Wowhead is of great help too when looking for a list of IDs to track: my general approach is to look up the associated achievement, which will then link to all the associated rares and IDs.

I haven’t created modules for the other zones, because I don’t really see a point in doing so—as I see it, they aren’t farmed actively, so it is unlikely that other players are able to share data on kill timers. In contrast, the rares are part of the main zone activity in zones like Korthia, and hence, it is more likely for data to be present too.

Thank you for the questions though! I hope I answered them to a satisfactory level.
